275: Update user's password
supertokens/supertokens-core pull request #291
Opened 2021-08-01 22:58 UTC by dulowski-marek

## Summary of change
This reuses the reset password logic to allow changing user's password in EmailPassword recipe. The http controllers logic is kept separate to not tie this unnecessarily to reset password more than needed. It would be best, if reset password and change password logic was extracted to separate, common function,

## Related issues
- https://github.com/supertokens/supertokens-core/issues/275

## Test Plan
1. Test API inputs
2. Redeem without correct token, should throw an error
3. Signin after change with correct token:
    **Given that:**
        - Bob is existing user within `EmailPassword` recipe
        - ...and he generates a password change token
        - ...and he generates a password change token
    **When:**
        - Bob redeems password change token
    **Then:**
        - Bob should be able to login with new password
4. Redeem after token expiry, should throw an error
5. Redeem token should remove existing sessions

## Documentation changes
(If relevant, please create a PR in our [docs repo](https://github.com/supertokens/docs), or create a checklist here highlighting the necessary changes)

## Checklist for important updates
- [x] Changelog has been updated
- [ ] ~`coreDriverInterfaceSupported.json` file has been updated (if needed)~
- [ ] ~Changes to the version if needed~
   - ~In `build.gradle`~
- [x] Had installed and ran the pre-commit hook
- [ ] ~If there are new dependencies that have been added in `build.gradle`, please make sure to add them in `implementationDependencies.json`.~
- [x] Issue this PR against the latest non released version branch.
   - To know which one it is, run find the latest released tag (`git tag`) in the format `vX.Y.Z`, and then find the latest branch (`git branch --all`) whose `X.Y` is greater than the latest released tag.
   - If no such branch exists, then create one from the latest released branch.

## Remaining TODOs for this PR
- [ ] API tests
- [ ] Logic tests
- [ ] Reuse reset password logic, but add active session removal.

2021-08-02 05:54 UTC, rishabhpoddar commented
- Please start by making changes to the CDI spec.
- This API is supposed to allow changing of a user's password or email by simply editing those fields in the db. No need to create any additional token etc.. So an APi like:
   ```
   /recipe/user PUT
   {
      userId: string,
      newPassword?: string,
      email?: string
   }
   ```
   "?" means they are optional. If the user has provided both those fields, both of them are changed. And the response can be:
   ```
   {
      status: "OK" | "EMAIL_ALREADY_EXISTS_ERROR"
   }
   ```
   The password validator would need to run in the backend SDK inside the recipe function that is used to call this API.
- Due to this large difference between what was expected and what is implemented, you should close this PR and start this from scratch.

2021-08-02 06:08 UTC, dulowski-marek commented
Why do you think such API would be better than 2 endpoints allowing to separately change user's credentials? How is that different from password reset?
How do you want to approach change password request validation, if you can change the email in the same request? 

There are reasons why I chose to do two separate requests and token generation for password change. I don't know yours for the API design that you proposed at this moment, so please explain.

2021-08-02 06:10 UTC, rishabhpoddar commented
> Why do you think such API would be better than 2 endpoints allowing to separately change user's credentials?

Because this is not a password reset flow.. it's simply one of the CRUD operations we provide to the backend against the objects of this recipe.


> How do you want to approach change password request validation, if you can change the email in the same request?

What is password request validation?

> There are reasons why I chose to do two separate requests and token generation for password change. I don't know yours for the API design that you proposed at this moment, so please explain.

My logic is simply to provide CRUD operation on the objects of this recipe. That's all. The actual password reset flow is different. Happy to discuss on a call.

2021-08-09 09:04 UTC, dulowski-marek commented
Then this PR provides simple CRUD without session removal logic.

2021-08-14 07:15 UTC, rishabhpoddar requested changes

2021-08-14 07:15 UTC, rishabhpoddar commented on CHANGELOG.md
> +- Add dedicated `POST /recipe/user/password/change/token` and `POST /recipe/user/password/change` endpoints allowing to
The changelog message is wrong.

2021-08-14 07:15 UTC, rishabhpoddar commented on src/main/java/io/supertokens/webserver/api/emailpassword/UpdateEmailOrPasswordAPI.java
> +        return "/recipe/user/credentials";
Should change to `/recipe/user`

2021-08-14 07:15 UTC, rishabhpoddar commented on src/main/java/io/supertokens/webserver/api/emailpassword/UpdateEmailOrPasswordAPI.java
> +        String userId = InputParser.parseStringOrThrowError(input, "method", false);
- Mistake - no "method", should be "userId"?
- Not tested API properly.

2021-08-14 07:15 UTC, rishabhpoddar commented on src/test/java/io/supertokens/test/emailpassword/UpdateUsersEmailAndPasswordTest.java
> +/*
- Need to add API test as well
- Add a test to update info of a user if they don't exist - should return status: "UNKNOWN_USER_ID"

2021-08-14 07:15 UTC, rishabhpoddar commented on src/main/java/io/supertokens/webserver/api/emailpassword/UpdateEmailOrPasswordAPI.java
> +            super.sendJsonResponse(200, result, resp);
The API output should be 
```
{
   status: "OK" | "UNKNOWN_USER_ID_ERROR"
}
```

2021-08-14 07:21 UTC, rishabhpoddar requested changes

2021-08-14 07:21 UTC, rishabhpoddar commented on src/main/java/io/supertokens/emailpassword/EmailPassword.java
> +            if (email != null) {
- You will first want to take a lock on all this userId's row by using a select for update query (which should already exist in the plugin interface).
- Then if the userId doesn't exist, you would return `"UNKNOWN_USER_ID_ERROR"`, else continue.

2021-08-21 09:36 UTC, rishabhpoddar approved these changes

2021-08-21 12:41 UTC, merged