feat: adds migration api and queries
supertokens/supertokens-core pull request #503
Opened 2022-09-06 08:09 UTC by jscyo

## Summary of change
(A few sentences about this PR)

## Related issues
- Link to issue1 here
- Link to issue1 here

## Test Plan
(Write your test plan here. If you changed any code, please provide us with clear instructions on how you verified your changes work. Bonus points for screenshots and videos!)

## Documentation changes
(If relevant, please create a PR in our [docs repo](https://github.com/supertokens/docs), or create a checklist here highlighting the necessary changes)

## Checklist for important updates
- [ ] Changelog has been updated
    - [ ] If there are any db schema changes, mention those changes clearly
- [ ] `coreDriverInterfaceSupported.json` file has been updated (if needed)
- [ ] `pluginInterfaceSupported.json` file has been updated (if needed)
- [ ] Changes to the version if needed
   - In `build.gradle`
- [ ] Had installed and ran the pre-commit hook
- [ ] If there are new dependencies that have been added in `build.gradle`, please make sure to add them in `implementationDependencies.json`.
- [ ] Issue this PR against the latest non released version branch.
   - To know which one it is, run find the latest released tag (`git tag`) in the format `vX.Y.Z`, and then find the latest branch (`git branch --all`) whose `X.Y` is greater than the latest released tag.
   - If no such branch exists, then create one from the latest released branch.

## Remaining TODOs for this PR
- [ ] Item1
- [ ] Item2

2022-09-07 12:01 UTC, rishabhpoddar requested changes

2022-09-07 12:01 UTC, rishabhpoddar commented on src/main/java/io/supertokens/emailpassword/PasswordHashing.java
> +    public boolean isInputAValidPasswordHash(String hash) {
change name for make it more clear.

2022-09-07 12:01 UTC, rishabhpoddar commented on src/main/java/io/supertokens/emailpassword/PasswordHashing.java
> +    public boolean isInputAValidPasswordHash(String hash) {
What if i forget to modify this function??

2022-09-07 13:14 UTC, rishabhpoddar requested changes

2022-09-07 13:14 UTC, rishabhpoddar commented on src/main/java/io/supertokens/emailpassword/PasswordHashing.java
> +        return (hash.startsWith("$argon2id") || hash.startsWith("$2a") || hash.startsWith("$2x")
also argon2 + others..

2022-09-07 13:14 UTC, rishabhpoddar commented on src/test/java/io/supertokens/test/emailpassword/UserMigrationTest.java
> +                    .importUserWithPasswordHashOrUpdatePasswordHashIfUserExists(process.main, email, passwordHash);
```suggestion
                    .importUserWithPasswordHash(process.main, email, passwordHash);
```

2022-09-07 13:14 UTC, rishabhpoddar commented on src/test/java/io/supertokens/test/emailpassword/UserMigrationTest.java
> +    // test bcrypt with different salt rounds
wrong comment

2022-09-07 13:14 UTC, rishabhpoddar commented on src/test/java/io/supertokens/test/emailpassword/UserMigrationTest.java
> +    }
need to also add for different argon2 types + different config for 2id

2022-09-09 05:23 UTC, rishabhpoddar requested changes

2022-09-09 05:23 UTC, rishabhpoddar commented on src/main/java/io/supertokens/emailpassword/EmailPassword.java
> +        }
```suggestion
            passwordHash = PasswordHashing.getInstance(main).updatePasswordHashWithPrefixIfRequired(hashingAlgorithm,
                    passwordHash);
      if (!PasswordHashing.getInstance(main).doesSuperTokensSupportInputPasswordHashFormat(passwordHash)) {
            throw new UnsupportedPasswordHashingFormatException("Unsupported password hashing format");
        }
```

2022-09-09 05:23 UTC, rishabhpoddar commented on src/main/java/io/supertokens/emailpassword/PasswordHashing.java
> +        if (hashingAlgorithm.equals(PasswordHashingAlgorithm.ARGON2)) {
do null check here

2022-09-09 06:12 UTC, jscyo commented
## FLOWS
When passing hashing algorithm

Bcrypt + valid passwordHash ->  success
Bcrypt + passwordHash that is not bcrypt format -> 400 Error: password hash not in bcrypt format

Argon2 + validPasswordHash -> success
Argon2 + passwordHash that is not argon2 format -> 400 Error: password hash not in argon2 format 

Scrypt + validPasswordHash(supertokens scrypt format | random string) -> success
Scrypt + invalidPasswordHash (other password hashes format) -> 400 Error: password hash not in scrypt format

Without passing hashing algorithm

random string -> Error: invalid password hashing format

Bcrypt format password hash -> success
Argon2 format password hash -> success

Scrypt format password hash(supertokens format) -> success

2022-09-09 07:07 UTC, rishabhpoddar commented on src/test/java/io/supertokens/test/emailpassword/api/ImportUserWithPasswordHashAPITest.java
> +            requestBody.addProperty("hashingAlgorithm", "bcrypt");
test with capital and random BcRyPT also

2022-09-19 13:16 UTC, rishabhpoddar approved these changes

2022-09-19 13:21 UTC, rishabhpoddar approved these changes

2022-09-19 13:22 UTC, merged